---
development:
  dialect: postgres
  database: postgres
  user: postgres
  password: 1337
  host: 127.0.0.1
  pool: 5
  port: 5432

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/saloon_test?sslmode=disable"}}
#
#production:
#  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/saloon?sslmode=disable"}}

# docker run --name pyc-postgres -e POSTGRES_PASSWORD=1337 -p 5432:5432 -d postgres